# Generated by Django 3.2.5 on 2021-07-08 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_register_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
