# Generated by Django 3.2.5 on 2021-07-08 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_register_table_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='last_name',
        ),
        migrations.AddField(
            model_name='register_table',
            name='contact_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
