# Generated by Django 3.2.5 on 2021-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_register_table_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
