# Generated by Django 3.2.5 on 2021-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='chater_no',
            new_name='chapter_no',
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='content',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='content',
            name='module_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='content',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='resource/%Y/%m/%d'),
        ),
    ]
