# Generated by Django 3.2.5 on 2022-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_course',
            name='topics',
            field=models.TextField(default=''),
        ),
    ]
