# Generated by Django 3.2.5 on 2022-05-27 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_shedule',
            name='reminder',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
